# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

# Scrape prometheus 
#   - job_name: 'prometheus'
#     # Override the global default and scrape targets from this job every 5 seconds.
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:9090']

# Scrape Grafana 
#   - job_name: 'grafana_metrics'
#     scrape_interval: 15s
#     scrape_timeout: 5s
#     static_configs:
#       - targets: ['localhost:3000']

# Scrape meteo
#   - job_name: 'meteo-fiobbio'
#     static_configs:
#     - targets: ['localhost:7979']
# 
#   - job_name: 'meteo-misma'
#     static_configs:
#     - targets: ['localhost:7980']
# 
#   - job_name: 'meteo-villa'
#     static_configs:
#     - targets: ['localhost:7990']
# 
#   - job_name: 'meteo-lecco'
#     static_configs:
#     - targets: ['localhost:7991']

  - job_name: 'home-cancel'
    static_configs:
    #- targets: ['localhost:7981']
    - targets: ['10.0.0.200']

# Scrape the openwrt router
  - job_name: 'openwrt'
    scrape_interval: 15s
    metrics_path: '/metrics/openwrt'
    static_configs:
    - targets: ['jak.sba.lat']

# Scrape the xiaomi-openwrt AP
  - job_name: 'xiaomi-openwrt'
    scrape_interval: 15s
    metrics_path: '/metrics/xiaomi'
    static_configs:
    - targets: ['jak.sba.lat']

#   - job_name: 'dnsmasq'
#     scrape_interval: 60s
#     metrics_path: '/metrics/dns'
#     static_configs:
#     - targets: ['jak.sba.lat']
# 
#   - job_name: 'nginx'
#     scrape_interval: 60s
#     metrics_path: '/metrics/nginx'
#     static_configs:
#     - targets: ['jak.sba.lat']

#  - job_name: 'nginx-fiobbio'
#    scrape_interval: 60s
#    metrics_path: '/metrics/nginx'
#    scheme: https
#    static_configs:
#    - targets: ['meteo.fiobbio.com']

# Scrape this endpoint via node
#   - job_name: 'nodel-local'
#     scrape_interval: 15s
#     metrics_path: '/metrics'
#     static_configs:
#     - targets: ['localhost:9100']


#   - job_name: 'cadvisor-local'
#     scrape_interval: 15s
#     metrics_path: '/metrics'
#     static_configs:
#     - targets: ['localhost:8080']
# 
#   - job_name: 'fiobbio-rpi'
#     scrape_interval: 60s
#     metrics_path: '/metrics/node'
#     scheme: https
#     static_configs:
#     - targets: ['meteo.fiobbio.com']

#  - job_name: 'grafana-image'
#    scrape_interval: 60s
#    metrics_path: '/metrics'
#    static_configs:
#    - targets: ['localhost:8081']
